### ISSUE TITLE
no matching function for call to 'TwoWire::begin(int&, int&)

### ISSUE THREAD

**Issue by roger-tannous** [MSZ98/pcf8574#1]
Hello, in src/pcf8574.h

There's an error with the call to Wire.begin(SDA, SCL);

It should be Wire.begin(address);

**Comment by MSZ98** [comment]
This is kinda strange, looks like your MCU does not support I2C master or something. Can you provide some more info? What board are you using?

**Comment by roger-tannous** [comment]
Hi,

My board is Arduino Nano.

But regardless of the board/MCU, the invocation for the begin function
broke the definition from the Arduino's documentation library itself.


Best Regards,

**Comment by MSZ98** [comment]
Fixed, you can update to 1.0.1 and it should work as expected. That was a problem with compatibility between ESP32 libraries and Arduino Wire library. Use one of the pcf8574 -> Arduino examples. When I get some free time, I'll make some more docs and repairs..
